<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{972b3bb0-0ef7-4b5c-929a-ef97236f553a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_test:Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_test();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>